### ISSUE TITLE
Add a season value corresponding to the liturgical season to the API results

### ISSUE THREAD

**Issue by matthewa26** [Liturgical-Calendar/LiturgicalCalendarAPI#173]
**A clear and concise description of what the problem is.**
I would like to have a clear way of knowing what liturgical season a particular date is in, so that when looking at the calendar, it is clear what the season is.

**Describe the solution you'd like**
Having an optional parameter for providing the liturgical season in the API results. This would be optional for backwards compatibility with the current API version, defaulting to false for anyone who has not included it as a parameter in their query.

**Describe alternatives you've considered**
I've considered calculating this using existing data from the API, but the issue is that this data may be inconsistent across different calendar versions.

**Additional context**
This will be used to show the liturgical calendar in a GUI in an iOS application.

**Comment by JohnRDOrazio** [comment]
Thank you Matthew for taking interest in this project! I am currently traveling until September 5th. Hopefully I will be able to look into this shortly after I return from my travels.

**Comment by JohnRDOrazio** [comment]
Implemented in commits https://github.com/Liturgical-Calendar/LiturgicalCalendarAPI/commit/83175c981af67f9bf482b07fdf320e942a82cd71 and https://github.com/Liturgical-Calendar/LiturgicalCalendarAPI/commit/ece33dd3259c7b0436da8a2ff7ed9587afb0c0ec (stupid mistake! mah, happens)
