### ISSUE TITLE
Add slovak (sk) language to weblate

### ISSUE THREAD

**Issue by misa1515** [Liturgical-Calendar/LiturgicalCalendarAPI#233]
Please add slovak language (sk) to the weblate.
Thank you.

**Comment by JohnRDOrazio** [comment]
Hello misa, I added Slovak to sober of the main components: 
https://translate.johnromanodorazio.com/projects/liturgical-calendar/-/sk/

Thank you for contributing, just a reminder that the names of the liturgical memorials and feasts should correspond with the Roman Missal published in the region.

May I ask what brought your interest to this project? How are you thinking of using the project?
