### ISSUE TITLE
ICS Error

### ISSUE THREAD

**Issue by mdecaro** [Liturgical-Calendar/LiturgicalCalendarAPI#67]
Still getting an error:

<br />
<b>Warning</b>:  Undefined property: stdClass::$published_at in <b>/var/www/vhosts/johnromanodorazio.com/httpdocs/LiturgicalCalendar/LitCalEngine.php</b> on line <b>2731</b><br />
<br />
<b>Fatal error</b>:  Uncaught Error: Call to undefined function ParseColorString() in /var/www/vhosts/johnromanodorazio.com/httpdocs/LiturgicalCalendar/LitCalEngine.php:2769
Stack trace:
#0 /var/www/vhosts/johnromanodorazio.com/httpdocs/LiturgicalCalendar/LitCalEngine.php(3073): LitCalEngine-&gt;generateResponse()
#1 /var/www/vhosts/johnromanodorazio.com/httpdocs/LiturgicalCalendar/LitCalEngine.php(73): LitCalEngine-&gt;Init()
#2 {main}
  thrown in <b>/var/www/vhosts/johnromanodorazio.com/httpdocs/LiturgicalCalendar/LitCalEngine.php</b> on line <b>2769</b><br />

**Comment by JohnRDOrazio** [comment]
I believe you are using an old endpoint. The latest dev endpoint can be found at https://litcal.johnromanodorazio.com/api/dev/LitCalEngine.php . Here is an example of ICS for the United States in the year 2025:

https://litcal.johnromanodorazio.com/api/dev/LitCalEngine.php?year=2025&nationalpreset=USA&returntype=ICS

There just happened to be another warning for the year 2025, since Saints Jean Brebeuf and companion martyrs falls on a Sunday that year, I was trying to output the name of the liturgical event when it didn't exist. Fixed in commit 10a6406a9a6d529c7218fcd5b45b4ae23a86367e .

**Comment by mdecaro** [comment]
When do these changes get added to the production server?

**Comment by JohnRDOrazio** [comment]
There isn't a deadline. They'll be added when the development is stable enough to be passed to the production server. I think it should be fairly ready within the next week or so though.

**Comment by mdecaro** [comment]
Thanks for being so responsive, and for a great app!

**Comment by JohnRDOrazio** [comment]
I believe that with the latest updates to the development branch, ICS generation should now be working correctly:

* 2f58d24756079cf690fb94b0c4d40b4ac11ad06c create LitCommon enum
* 22199b5b521b1647014252911b1a3721ec54b7b5 fix LitCommon i18n
* e16d1faff4256797e790f451caebfac0fe9bb34e fix StJaneFrancesNewDate error for Sunday coincidence
* 87c6720bf14504cd32ab216fd7a3b9941ab9355f fix latin strings in LitCalAPI

I have run these tests, and they all seem to be working correctly for me:
* https://litcal.johnromanodorazio.com/api/dev/LitCalEngine.php?year=2029&nationalpreset=USA&returntype=ICS
* https://litcal.johnromanodorazio.com/api/dev/LitCalEngine.php?year=2025&nationalpreset=USA&returntype=ICS
* https://litcal.johnromanodorazio.com/api/dev/LitCalEngine.php?year=2025&nationalpreset=ITALY&returntype=ICS
* https://litcal.johnromanodorazio.com/api/dev/LitCalEngine.php?year=2025&returntype=JSON
* https://litcal.johnromanodorazio.com/api/dev/LitCalEngine.php?year=2025&nationalpreset=ITALY&returntype=JSON
* https://litcal.johnromanodorazio.com/api/dev/LitCalEngine.php?year=2025&nationalpreset=USA&returntype=JSON

Can you confirm on your end?

**Comment by JohnRDOrazio** [comment]
I've done a little more cleanup : 
* 1c742a8458027e1e56c036999807eb7e45c7d847 make LitGrade constructable
* 4d6dd7a548bf51c1751627360b77aff966c687de make sure 'from the common' is translated into latin

**Comment by mdecaro** [comment]
Excellent, working fine for me.

Thanks.  Is it possible to let me know when this works its way into the production server - If a problem, no sweat.

**Comment by JohnRDOrazio** [comment]
Hello @mdecaro , not sure how else to let you know, I have just released v3.0 of the API. The presentation website has been updated to reflect these changes, and had started using the v3 endpoint:
* Website: https://litcal.johnromanodorazio.com/
* Liturgical Calendar API (liturgical data endpoint): https://litcal.johnromanodorazio.com/api/v3/LitCalEngine.php 
* Liturgical Calendar API (metadata endpoint): https://litcal.johnromanodorazio.com/api/v3/LitCalMetadata.php
* Liturgical Calendar API (Dates of Easter endpoint): https://litcal.johnromanodorazio.com/api/v3/DateOfEaster.php

**Comment by mdecaro** [comment]
Much appreciated, thanks.

**Comment by JohnRDOrazio** [comment]
Are you by chance on our slack workspace "Catholic Devs" ? Feel free to join if you haven't already!
https://join.slack.com/t/catholicdevs/shared_invite/zt-dz50teya-019q4Zake3JdmsWiTxRBBg
